FROM tiangolo/uvicorn-gunicorn:python3.8-slim

COPY . /app/Backend/

WORKDIR /app/Backend/
ENV PORT=$PORT

RUN pip install torch==1.8.1+cpu torchvision==0.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install -r requirements.txt

EXPOSE $PORT
CMD uvicorn main:app --host 0.0.0.0 --port $PORT