FROM tiangolo/uvicorn-gunicorn:python3.8-slim

COPY . /app/Backend/

WORKDIR /app/Backend/

RUN pip install torch==1.8.1+cpu torchvision==0.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install -r requirements.txt

EXPOSE 8000