export const classes = ['Apple -- Apple Scab',
    'Apple -- Black Rot',
    'Apple -- Cedar Apple Rust',
    'Apple -- Healthy',
    'Cherry -- Powdery Mildew',
    'Cherry --  Healthy',
    'Corn -- Gray Leaf Spot (Cercospora Leaf Spot)',
    'Corn -- Common Rust',
    'Corn -- Northern Leaf Blight',
    'Corn -- Healthy',
    'Grape -- Black Rot',
    'Grape -- Esca (Black Measles)',
    'Grape -- Leaf Blight (Isariopsis Leaf Spot)',
    'Grape -- Healthy',
    'Peach -- Bacterial_spot',
    'Peach -- Healthy',
    'Pepper Bell -- Bacterial Spot',
    'Pepper Bell -- Healthy',
    'Potato -- Early Blight',
    'Potato -- Late Blight',
    'Potato -- Healthy',
    'Strawberry -- Leaf Scorch',
    'Strawberry -- Healthy',
    'Tomato -- Bacterial Spot',
    'Tomato -- Early Blight',
    'Tomato -- Late Blight',
    'Tomato -- Leaf Mold',
    'Tomato -- Septoria Leaf Spot',
    'Tomato -- Two-spotted Spider Mites',
    'Tomato -- Target Spot',
    'Tomato -- Yellow Leaf Curl Virus',
    'Tomato -- Mosaic Virus',
    'Tomato -- Healthy']